defaults:
  - _self_

dataset:
  name: c4 
  subset: realnewslike/train 

tokenizer:        
  name: EleutherAI/gpt-neo-125M/


train:
  output_dir: 
  logging_dir:
  use_peft : 
  lora_alpha :
  lora_r : 


hydra:
  run:
    dir: "./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}"


